### ISSUE TITLE
babel-plugin-flow-runtime: Does not play well with new babel beta

### ISSUE THREAD

**Issue by 0rvar** [codemix/flow-runtime#206] opened 2018-05-31 08:33 UTC
Switching to the new babel version (@babel/core and friends 7.0.0 beta) with preset-env causes failing builds until the flow-runtime is removed from .babelrc

**Comment by jedwards1211** [comment] 2018-05-31 19:55
Dupe of #184

**Closed by jedwards1211** 2018-05-31 19:55 UTC
