### ISSUE TITLE
Object destructive assignment on arguments is broken

### ISSUE THREAD

**Issue by mizchi** [codemix/flow-runtime#54] opened 2017-02-20 01:40 UTC
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validatosr
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### Broken code

This code is broken.

```js
/* @flow */

export default function update (
  {id, title, body}: {
    id: number,
    title: string,
    body: string
  }
): number {
  return id
}

```

Error

```
   3:
   4: export default function update (
   5:   { id, title, body }: {

  Error: arguments[0].id must be a number

  Expected: number

  Actual: void

  -------------------------------------------------

  arguments[0].title must be a string

  Expected: string

  Actual: void

  -------------------------------------------------

  arguments[0].body must be a string

  Expected: string

  Actual: void

  _callee$ (packages/api/commands/update.js:4:16)
  tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
  GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:299:22)
  GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
  updateItem (packages/api/commands/updateItem.js:84:17)
  _callee$ (packages/api/commands/updateItem.test.js:14:9)
  tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
  GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:299:22)
  GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)

```

It looks flow-runtime  is going to handle `[id, title, body]`.

Next code passed correctly

```
/* @flow */
export default function update (
  obj: {
    id: number,
    title: string,
    body: string
  }
): number {
  const {id, title, body} = obj
  return id
}
```

### Which package versions are you using?

v0.5.0

**Comment by phpnode** [comment] 2017-02-24 22:27
@mizchi what were you calling this function with? It seems to work correctly for me.

**Comment by phpnode** [comment] 2017-02-24 22:30
If you're confused about the error message - `arguments[0]` it's because of how destructuring works with annotations

**Comment by phpnode** [comment] 2017-03-01 20:29
@mizchi going to close this as I can't reproduce it in 0.6.1, please let me know if it's still an issue and I'll reopen

**Closed by phpnode** 2017-03-01 20:29 UTC
Labels: more-info-required
