### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by ForbesLindesay** [codemix/flow-runtime#95] opened 2017-04-17 13:41 UTC
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

When I run code compiled with regenerator runtime, it throws "ReferenceError: regeneratorRuntime is not defined"

---

### What is the expected behaviour?

It should not throw an error.
---

### Which package versions are you using?

0.10.0

I'm using it in a browserify bundle.

My guess is that flow-runtime needs to be compiled with the babel-plugin-transform-runtime package.

**Comment by vicapow** [comment] 2017-04-22 23:45
see: https://github.com/codemix/flow-runtime/issues/35

tl;dr, add  `import 'regenerator-runtime/runtime';` somewhere before flow-runtime gets imported

**Comment by phpnode** [comment] 2017-04-23 00:22
Thanks, yes sorry this is a dupe of #35, I misread it. I don't want to include regenerator runtime directly because any projects that use generators will already be including it and it won't get deduped, it's a bit unfortunate and really I'd rather just ship the generators, but that causes even more tooling problems.

**Closed by phpnode** 2017-04-23 00:22 UTC
Labels: bug
