### ISSUE TITLE
Invalid Type Checking with babel-plugin?

### ISSUE THREAD

**Issue by bradennapier** [codemix/flow-runtime#126] opened 2017-07-02 22:10 UTC
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

This very well could be me doing something completely wrong.  Loving the package minus the issue I am having here.  It is actually occurring with EVERY value in my state - it seems to ignore my type annotations and instead infer the values automatically.

My type indicates that a value should be an optional object, but i am getting errors saying it must be undefined / void.

```js
export type UserProfileState = {
  username: string,
  userEmail: string,
  firstName: string,
  lastName: string,
  userLocale: string,
  userPhoneNumber: string,
  emailVerified: 'true' | 'false',
  phoneVerified: 'true' | 'false'
};

export type AuthUserState = {
  isAuthenticated: boolean,
  dealerIdentityID: ?string,
  userIdentityID?: string,
  profile: ?UserProfileState
};
```

```js
const getDefaultUserState = (): AuthUserState => ({
  isAuthenticated: false,
  dealerIdentityID: undefined,
  profile: undefined,
  payments: {},
  location: {},
  devices: [],
  data: {},
});
```

Now when I try to add the profile value to the state:

```
uncaught at handleUserAttributes RuntimeTypeError: Return Type.profile must be undefined

Expected: void

Actual: {
  userAddress: string;
  emailVerified: string;
  phoneVerified: string;
  username: string;
  userLocale: string;
  firstName: string;
  userPhoneNumber: string;
  lastName: string;
  userEmail: string;
}
```

Editor doesn't have an issue when i manually do everything so I am guessing its a quirk of how everything ends up being built perhaps?

---

### What is the expected behaviour?

The profile value should use the UserProfile state 

---

### Which package versions are you using?

```json
"flow-runtime": "^0.13.0"
```

```json
"babel-plugin-flow-runtime": "^0.11.1"
```

**Comment by bradennapier** [comment] 2017-07-02 22:31
On further review, it actually appears like this is related to the generics bug that was reported.  I do not think it is handling generics properly.

The actual error appears to be coming from:

```js
authUser: <S: AuthUserState>(state: S, action: AuthUserAction): S => ({
    ...state,
    profile: action.profile,
  }),
```

If I change this to:

```js
authUser: (state: AuthUserState, action: AuthUserAction): AuthUserState => ({
    ...state,
    profile: action.profile,
  }),
```

It will begin working at this point.

**Comment by phpnode** [comment] 2017-11-14 14:19
This is almost certainly a dupe of #144, should be fixed in the next release.

**Closed by phpnode** 2017-11-14 14:19 UTC
